import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true });
const page = await (await browser.newContext({ viewport: { width: 1280, height: 1000 } })).newPage();
const errs = [];
page.on("pageerror", (e) => errs.push(e.message));
page.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); });
await page.goto("http://localhost:3000/admin/login");
await page.waitForTimeout(800);
await page.locator('input[name="username"]').fill("admin");
await page.locator('input[name="password"]').fill("admin123");
await page.locator('.admin-login-form button[type="submit"]').click();
await page.waitForTimeout(1500);
await page.goto("http://localhost:3000/admin");
await page.waitForTimeout(2500);
const found = await page.locator(".admin-sales-breakdown").count();
console.log("breakdown blocks on page:", found);
if (found === 0) console.log("BODY:", (await page.locator("body").innerText()).slice(0, 400));
console.log("errors:", errs.slice(0, 3).join(" || ") || "none");
await browser.close();
